#!/usr/bin/env python3
"""Synthesize hard-negative collisions via piper-sample-generator.

Reads `configs/examples/<project>/hard_negatives.yaml` (generated by
`init_wake.py` + optionally extended by `suggest_hard_negatives.py`), then
runs piper-sample-generator across every (bucket × phrase) pair. Each
bucket's `target_count` is distributed evenly across that bucket's phrases.

Output:
    data/<project>/synth/hard_negatives/
      ├── <bucket_id>__<phrase_slug>/*.wav
      └── manifest.jsonl              (rows tagged with bucket_id for per-bucket eval)

Usage:
    python scripts/synth_hard_negatives.py --project tofu
    python scripts/synth_hard_negatives.py --project tofu --count 5000   # override total
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent))
from synth_positives import (  # noqa: E402  — sibling import
    ensure_psg,
    ensure_standard_piper,
    generate_for_phrase,
    resolve_models,
    slug,
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--config", default=None,
                    help="Path to hard_negatives.yaml (default: configs/examples/<project>/hard_negatives.yaml)")
    ap.add_argument("--out", default=None,
                    help="Output root (default: data/<project>/synth/hard_negatives)")
    ap.add_argument("--count", type=int, default=None,
                    help="Override total hard-neg count (default: sum of bucket target_counts)")
    ap.add_argument("--batch-size", type=int, default=100)
    ap.add_argument("--max-speakers", type=int, default=904)
    ap.add_argument("--psg-dir", default="piper-sample-generator",
                    help="English generator checkout (not used for ONNX voices).")
    ap.add_argument("--model-cache", default="data/tts_models",
                    help="Cache directory for standard Piper ONNX voices.")
    args = ap.parse_args()

    cfg_path = Path(args.config) if args.config else Path(
        f"configs/examples/{args.project}/hard_negatives.yaml"
    )
    if not cfg_path.exists():
        print(f"ERROR: {cfg_path} not found. Run scripts/init_wake.py first.", file=sys.stderr)
        return 1
    cfg = yaml.safe_load(cfg_path.read_text())
    out_root = Path(args.out) if args.out else Path(f"data/{args.project}/synth/hard_negatives")
    out_root.mkdir(parents=True, exist_ok=True)

    buckets = cfg["buckets"]
    raw_total = sum(b["target_count"] for b in buckets)
    scale = (args.count / raw_total) if (args.count is not None and raw_total) else 1.0

    print(f"=== piper-sample-generator: hard-negatives for '{args.project}' ===", flush=True)
    print(f"  buckets:  {len(buckets)}")
    print(f"  out:      {out_root}")
    print(flush=True)

    piper_cfg = next((e for e in cfg.get("engines", []) if e.get("name") == "piper"), {})
    uses_english_generator = piper_cfg.get("voices", "ALL") == "ALL"
    try:
        if not uses_english_generator:
            ensure_standard_piper()
        psg_dir = (
            ensure_psg(Path(args.psg_dir))
            if uses_english_generator else Path(args.psg_dir)
        )
        models = resolve_models(
            cfg, psg_dir if uses_english_generator else None, Path(args.model_cache)
        )
    except (OSError, ValueError, RuntimeError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    print(f"  models:   {', '.join(m.name for m in models)}", flush=True)
    length_scales = [float(v) for v in cfg.get("variation", {}).get("speeds", [])]

    manifest_rows: list[dict] = []
    shortfalls: list[tuple[str, str, int, int]] = []
    for bucket in buckets:
        bid = bucket["id"]
        bucket_count = max(1, int(round(bucket["target_count"] * scale)))
        phrases = bucket["phrases"]
        if not phrases:
            print(f"  ⚠ bucket {bid}: no phrases, skipping", flush=True)
            continue
        per_phrase = max(1, bucket_count // len(phrases))
        print(f"  bucket {bid}: {len(phrases)} phrases × {per_phrase} samples = {per_phrase*len(phrases)}", flush=True)
        for phrase in phrases:
            phrase_dir = out_root / f"{bid}__{slug(phrase)}"
            actual, ok = generate_for_phrase(psg_dir, phrase, phrase_dir, per_phrase,
                                             batch_size=args.batch_size,
                                             max_speakers=args.max_speakers,
                                             models=models,
                                             length_scales=length_scales)
            if not ok:
                shortfalls.append((bid, phrase, actual, per_phrase))
            for wav in sorted(phrase_dir.glob("*.wav")):
                manifest_rows.append({
                    "file_id": f"{bid}__{slug(phrase)}__{wav.stem}",
                    "wav_path": str(wav),
                    "phrase": phrase,
                    "bucket_id": bid,
                    "label": "hard_negative",
                    "engine": (
                        "piper" if all(model.suffix == ".onnx" for model in models)
                        else "piper_sample_generator"
                    ),
                    "voice_model": ",".join(m.name for m in models),
                })

    if shortfalls:
        print("\n=== FAILED: some hard-negative phrases short of target ===", file=sys.stderr)
        for bid, phrase, actual, count in shortfalls:
            pct = 100 * actual / count if count else 0
            print(f"  ✗ {bid}/{phrase}: {actual}/{count} ({pct:.0f}%)",
                  file=sys.stderr)
        print("Not writing manifest. Wipe data/<project>/synth/hard_negatives "
              "and rerun; the pod disk likely had a transient I/O error "
              "(see RUNPOD_RECIPE.md).", file=sys.stderr)
        return 1

    mfp = out_root / "manifest.jsonl"
    with mfp.open("w") as f:
        for row in manifest_rows:
            f.write(json.dumps(row) + "\n")
    print(f"\n  wrote {mfp} ({len(manifest_rows)} rows)", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
